In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
#numpy array

In [4]:
my_list = [10,20,30,40]

In [5]:
type(my_list)

list

In [6]:
np.array(my_list)

array([10, 20, 30, 40])

In [7]:
my_numpy_array = np.array(my_list)

In [8]:
type(my_numpy_array)

numpy.ndarray

In [9]:
my_numpy_array

array([10, 20, 30, 40])

In [10]:
my_numpy_array[0]

10

In [11]:
my_numpy_array[-1]

40

In [12]:
my_numpy_array[0] = 100

In [13]:
my_numpy_array

array([100,  20,  30,  40])

In [14]:
my_numpy_array.max()

100

In [15]:
my_numpy_array.min()

20

In [16]:
my_numpy_array.mean()

47.5

In [17]:
matrix_list = [[1,0,0],[0,1,0],[0,0,1],[0,0,0]]

In [18]:
type(matrix_list)

list

In [19]:
matrix_list[0][0]

1

In [20]:
numpy_matrix_list = np.array(matrix_list)

In [21]:
numpy_matrix_list

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [22]:
numpy_matrix_list[0]

array([1, 0, 0])

In [23]:
numpy_matrix_list[0][0]

1

In [24]:
numpy_matrix_list.shape

(4, 3)

In [25]:
#arrange

In [26]:
range(0,10)

range(0, 10)

In [27]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [28]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [30]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [33]:
#linspace

In [34]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [35]:
#random

In [36]:
np.random.randint(1,10,3)

array([3, 1, 7])

In [37]:
np.random.randint(1,100,10)

array([25, 71, 10, 43,  4, 95, 42, 60, 50, 79])

In [38]:
#numpy arrays methods

In [39]:
my_numpy_list = np.arange(0,20)

In [40]:
my_numpy_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
my_numpy_list[4]

4

In [42]:
my_numpy_list[4:9]

array([4, 5, 6, 7, 8])

In [43]:
my_numpy_list[4:9:2]

array([4, 6, 8])

In [44]:
my_list = list(range(0,20))

In [45]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [46]:
my_list[4:9:2]

[4, 6, 8]

In [47]:
#my_list[4:9] = 10

In [48]:
my_numpy_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
my_numpy_list[4:9] = -10 

In [50]:
my_numpy_list

array([  0,   1,   2,   3, -10, -10, -10, -10, -10,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [51]:
other_list = np.arange(0,15)

In [52]:
other_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
other_list[4:10]

array([4, 5, 6, 7, 8, 9])

In [54]:
slicing_list = other_list[4:10]

In [55]:
slicing_list

array([4, 5, 6, 7, 8, 9])

In [56]:
other_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
 slicing_list[0]

4

In [58]:
 slicing_list[:] = 100

In [59]:
slicing_list

array([100, 100, 100, 100, 100, 100])

In [60]:
other_list

array([  0,   1,   2,   3, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14])

In [61]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [62]:
slicing_my_list = my_list[4:9]

In [63]:
slicing_my_list

[4, 5, 6, 7, 8]

In [64]:
slicing_my_list[0] = -100

In [65]:
slicing_my_list[1] = -100

In [66]:
slicing_my_list

[-100, -100, 6, 7, 8]

In [67]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [68]:
numpy_list_3 = np.arange(0,20)

In [69]:
numpy_list_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [70]:
numpy_list_3_copy = numpy_list_3.copy()

In [71]:
numpy_list_3_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [72]:
slicing_3 = numpy_list_3_copy[4:9]

In [73]:
slicing_3

array([4, 5, 6, 7, 8])

In [74]:
slicing_3[:] = -100

In [75]:
slicing_3

array([-100, -100, -100, -100, -100])

In [76]:
numpy_list_3_copy

array([   0,    1,    2,    3, -100, -100, -100, -100, -100,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19])

In [77]:
numpy_list_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [78]:
#numpy operations with numpy arrays

In [79]:
new_array = np.random.randint(1,150,25)

In [80]:
new_array

array([131, 101,  35,  20,  11,  20, 146,   4,   2,  76,  62,  61,  93,
        46,  28,  59,   3,  61,  14, 139,  20,  66,  15,  59, 126])

In [81]:
new_array > 50

array([ True,  True, False, False, False, False,  True, False, False,
        True,  True,  True,  True, False, False,  True, False,  True,
       False,  True, False,  True, False,  True,  True])

In [82]:
result_array = new_array > 50

In [83]:
result_array

array([ True,  True, False, False, False, False,  True, False, False,
        True,  True,  True,  True, False, False,  True, False,  True,
       False,  True, False,  True, False,  True,  True])

In [84]:
new_array

array([131, 101,  35,  20,  11,  20, 146,   4,   2,  76,  62,  61,  93,
        46,  28,  59,   3,  61,  14, 139,  20,  66,  15,  59, 126])

In [85]:
new_array[result_array]

array([131, 101, 146,  76,  62,  61,  93,  59,  61, 139,  66,  59, 126])

In [86]:
last_array = np.arange(0,30)

In [87]:
last_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [88]:
last_array + last_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [89]:
last_array * last_array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729, 784, 841])

In [90]:
last_array - last_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [91]:
last_array / last_array

C:\Users\Mustafa\AppData\Local\Temp\ipykernel_16496\3398326563.py:1: RuntimeWarning: invalid value encountered in divide
  last_array / last_array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [92]:
last_array.max()

29

In [93]:
last_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [94]:
np.max(last_array)

29

In [95]:
np.mean(last_array)

14.5

In [96]:
np.sqrt(last_array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481])